### ISSUE TITLE
suggest: read trove.yml in the current directory (or load with option)

### ISSUE THREAD

**Issue by kyoto7250** [Hyde46/hoard#115]
Many projects use Makefile, gradle, and npm and more to configure commands for their project, but we often need to read the code inside because those tools are difficult to write a detailed description.

If `hoard` have the ability to read `trove.yml` in the current directory, we will be able to search for those commands and give them descriptions.

This makes it possible to add trove.yml to each repository to manage commands.

```
# project root
Makefile # declare command
trove.yml # search, and execute in Makefile command.
```

---

Whether to load automatically or optionally needs to be discussed.

**Comment by Hyde46** [comment]
Are you interested in working on this @kyoto7250 ?
There's a couple of methods already present for the [merging logic](https://github.com/Hyde46/hoard/blob/main/src/command/trove.rs#L136) of trove files.

**Comment by kyoto7250** [comment]
@Hyde46 
OK, could you assign this issue to me?

**Comment by kyoto7250** [comment]
As I understand it now.

- Files in the current directory are automatically read
- Merged commands can be displayed by pressing a key in the TUI.
- And, there is a setting in `config.yml` to display merged commands from the beginning.

**Comment by Hyde46** [comment]
After having thought about it a bit more, adding the merge functionality with conditional visualization of either the local trove, global trove or the merge needs a little more work on the data model. Since there's no way to distinguish the two after merging.

So for now we can split this up and make this PR only touch on the loading of local troves.
As I see it, you could add a new function somewhere around this [block](https://github.com/Hyde46/hoard/blob/main/src/hoard.rs#L179) which checks if a trove file is present in the current working directory. If there is a local trove file present, only run `commands_gui::run()` with the local trove file that was found [here](https://github.com/Hyde46/hoard/blob/main/src/hoard.rs#L185).

Additionally, a config field which can turn off this functionality would be nice
