### ISSUE TITLE
Allow name-based / num-based parameter tokens

### ISSUE THREAD

**Issue by khuongduybui** [Hyde46/hoard#151]
For example, I have a command that reuses a parameter many times like this:
`echo hello #; echo I hope you find this message well, #; echo goodbye, #`

Although there are three `#` placeholders, they are all for the same param.
If I put such a command into `hoard` today, when picking it, I will have to supply the same name "John" 3 times to get
`echo hello John; echo I hope you find this message well, John; echo goodbye, John`

What if I can tell hoard that those are the same parameter, such as:
`echo hello #name; echo I hope you find this message well, #name; echo goodbye, #name`
And when picking the command, instead of being asked for the first, second, and third params, I simply get asked for the `name` param?

**Comment by Hyde46** [comment]
I think i've considered this case shortly when implementing the parameter tokens, but forgot about it.
Great point you are raising, this should be implemented. 
I'll try to make some free time for this 😄

**Comment by Hyde46** [comment]
@khuongduybui Named parameters are now possible on master! If you feel comfortable building this by hand, you can replace the hoard bin with where you have installed your old version and get access to it immediately. :rocket: 

Otherwise I'll make a release with this and a couple of bug fixes sometime this or next week

**Comment by khuongduybui** [comment]
Tyvm
